language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci
  
script:
  - CI='' npm run build

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: bullcenter-frontend
  skip-cleanup: true
  on:
    all_branches: true
