language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci
script:
  - CI='' npm run build

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master